
spring:
  redis:
    #    host: 127.0.0.1
    #    port: 6379
    pattern: cluster
    cluster:
      nodes: 127.0.0.1:6379
    password:
    ## Redis数据库索引(默认为0)
    database: 0
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 30000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  profiles:
    active: dev
logging:
  config: classpath:log4j2.xml
  level:
    com.tong: info
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.tong.consume.bean.response
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 自动驼峰命名
  map-underscore-to-camel-case: false
  ## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
  logging:
    level:
      com.tong.consume.mapper: debug

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: customerbasic-group-test-tong
    #目的地（topic:tag）
    #topic
    topic: customerbasic-topic-test-tong
    #消息发送超时时长，默认3s
    send-message-timeout: 3000
    #sync tag(同步消息tag)
    sync-tag: anran-sync-tags
    #async tag(异步消息tag)
    async-tag: anran-async-tags
    #oneway tag(单向消息tag)
    oneway-tag: anran-oneway-tags
#消费者配置
mq:
  consumer:
    group: customerbasic-group-test-tong
    #监听主题
    topic: customerbasic-topic-test-tong